services:

  db:
    image: postgres:16
    container_name: intern_tracker_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: intern_tracker_backend

    environment:
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: intern_tracker_frontend

    ports:
      - "8080:80"

    depends_on:
      - backend


volumes:
  postgres_data: